package me.oska.plugins.orpg;

public enum SkillType {
    PLAYER_DAMAGE_PLAYER,
    PLAYER_DAMAGE_ENTITY,
    ENTITY_DAMAGE_PLAYER,
    PLAYER_SHOOT_BLOCK,
    PLAYER_SHOOT_ENTITY,
    PLAYER_SHOOT_PLAYER,
    ENTITY_SHOOT_PLAYER,
    PLAYER_SHOOT
}
